### ISSUE TITLE
you can range multiple regions, but you will have to merge in another call to the BeaconManager. Could you please provide sample??

### ISSUE THREAD

**Issue by chanti-github** [aritchie/beacons#1]
Hi @aritchie  sir,

Could you please provide sample for range multiple regions ??

**Comment by aritchie** [comment]
You could just provide a UUID without any major and take all of your UUID regions in.

You can also use the Observable.Merge:

```csharp
beaconManager
                .WhenBeaconRanged(...)
                .Merge(beaconManager.WhenBeaconRanged(...))
                .Merge(beaconManager.WhenBeaconRanged(...))
```
             
As a note, I never officially released this library because I never completely finished it.  Ranging is the only thing that is fully implemented

**Comment by chanti-github** [comment]
@aritchie sir,

Thank you so much
