### ISSUE TITLE
04-04 15:27:47.494 E/BluetoothLeScanner(29134): fail to start le scan - SecurityException thrown: java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results

### ISSUE THREAD

**Issue by chanti-github** [aritchie/beacons#2]
I am getting this exception in Android even i enable bluetooth and location
04-04 15:27:47.494 E/BluetoothLeScanner(29134): fail to start le scan - SecurityException thrown: java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results

**Comment by aritchie** [comment]
You need to actually request permission to use those services which is outside the scope of this library.  Please read the official documentation for google on permissions.

Please note that this is not a support channel.  If you need help beyond the samples and source, I do offer paid consultancy.
